name: Release

on:
  release:
    types: [created]

jobs:
  update-version-build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Update version in build.gradle.kts
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/^refs\/tags\/v//')
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" build.gradle.kts

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Publish to Akani Repository
        run: ./gradlew publish
        env:
          AKANI_REPO_USER: ${{ secrets.AKANI_REPO_USER }}
          AKANI_REPO_PASS: ${{ secrets.AKANI_REPO_PASS }}

      - name: Upload Paper JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./paper/build/libs/AkaniCore-paper.jar
          asset_name: AkaniCore-paper-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive

      - name: Upload Velocity JAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./velocity/build/libs/AkaniCore-velocity.jar
          asset_name: AkaniCore-velocity-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add build.gradle.kts
          git commit -m "Update version to $VERSION" || exit 0
          git push