name: AkaniCore
main: it.einjojo.akani.core.paper.PaperAkaniCorePlugin
version: ${version}
api-version: "1.20"
author: "EinJOJO @ Kalypzo.de"
website: https://kalypzo.de
description: AkaniCore has been created to provide a core for all Akani plugins.
depend:
  - LuckPerms
softdepend:
  - "CloudNet-Bridge"