name: AkaniCore
main: it.einjojo.akani.core.AkaniCorePaperPlugin
version: ${project.version}
api-version: 1.20
author: EinJoJo
description: AkaniCore has been created to provide a core for all Akani plugins.